#!/usr/bin/bash
if [ $(uname -m) == "aarch64" ]; then
    ARCH_CFLAGS="-mcpu=native"
else
    ARCH_CFLAGS="-march=native"
fi
BASE_CFLAGS="$ARCH_CFLAGS -Ofast -fno-plt"
BASE_LDFLAGS="-s -Wl,-O2,--gc-sections"
CLANG_CFLAGS="$BASE_CFLAGS -flto=full"
CLANG_LDFLAGS="$BASE_LDFLAGS -fuse-ld=lld"
GCC_CFLAGS="$BASE_CFLAGS -flto -flto-partition=none -fipa-pta -fno-semantic-interposition -fdevirtualize-at-ltrans -ffunction-sections -fdata-sections"
GCC_LDFLAGS="$BASE_LDFLAGS -fuse-linker-plugin"
