name: Ubuntu
run-name: Ubuntu (${{ github.event.inputs.ubuntu_version }}) ${{ github.sha }}

on:
  workflow_dispatch:
    inputs:
      ubuntu_version:
        type: choice
        description: Linux dist the workflow will run on
        required: true
        default: ubuntu-24.04
        options: 
          - ubuntu-24.04
          - ubuntu-24.04-arm
          - ubuntu-22.04
          - ubuntu-22.04-arm
      port_number:
        type: number
        description: Port number for frp service
        required: true
        default: 6000

jobs:
  build:
    runs-on: ${{ github.event.inputs.ubuntu_version }}
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - run: sudo ./init_root.sh
      - run: ./init.sh
      - run: ./run-frpc.sh
        env:
          INIT_PORT_NUMBER: ${{ inputs.port_number }}
          RUNNER_PASSWORD: ${{ secrets.RUNNER_PASSWORD }}
          FRPS_DOMAIN: ${{ secrets.FRPS_DOMAIN }}
          FRPC_TLS_KEY: ${{ secrets.FRPC_TLS_KEY }}
          FRPC_TLS_CERTIFICATE: ${{ secrets.FRPC_TLS_CERTIFICATE }}
          FRPC_TLS_CA_CERTIFICATE: ${{ secrets.FRPC_TLS_CA_CERTIFICATE }}
          SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
          RUNNER_IMAGE: ${{ inputs.ubuntu_version }}
