name: Ubuntu

on:
  workflow_dispatch:
    inputs:
      Linux:
        type: choice
        description: Linux dist the workflow will run on
        required: true
        default: ubuntu-22.04
        options: 
          - ubuntu-20.04
          - ubuntu-22.04
      mkswap:
        type: boolean
        description: Use whole /mnt as swap
        required: false
        default: false

jobs:
  build:
    runs-on: ${{ github.event.inputs.Linux }}
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - run: ./init.sh
      - run: ./mkswap.sh
        if: ${{ inputs.mkswap }}
      - run: ./install-frp.sh
      - name: run frpc
        env:
          RUNNER_PASSWORD: ${{ secrets.RUNNER_PASSWORD }}
          FRPS_DOMAIN: ${{ secrets.FRPS_DOMAIN }}
          FRPC_TLS_KEY: ${{ secrets.FRPC_TLS_KEY }}
          FRPC_TLS_CERTIFICATE: ${{ secrets.FRPC_TLS_CERTIFICATE }}
          FRPC_TLS_CA_CERTIFICATE: ${{ secrets.FRPC_TLS_CA_CERTIFICATE }}
          SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
        run: ./run-frpc.sh

