name: Windows
run-name: Windows (${{ github.event.inputs.Windows }}) ${{ github.sha }}

on:
  workflow_dispatch:
    inputs:
      Windows:
        type: choice
        description: Windows dist the workflow will run on
        required: true
        default: windows-2025
        options: 
          - windows-2025
          - windows-2022
      ssh:
        type: boolean
        description: Install OpenSSH
        required: true
        default: false
jobs:
  build:
    runs-on: ${{ github.event.inputs.Windows }}
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - run: ./init.ps1
        env:
          INIT_SSH: ${{ inputs.ssh }}
      - run: ./run-frpc.ps1
        env:
          RUNNER_PASSWORD: ${{ secrets.RUNNER_PASSWORD }}
          FRPS_DOMAIN: ${{ secrets.FRPS_DOMAIN }}
          FRPC_TLS_KEY: ${{ secrets.FRPC_TLS_KEY }}
          FRPC_TLS_CERTIFICATE: ${{ secrets.FRPC_TLS_CERTIFICATE }}
          FRPC_TLS_CA_CERTIFICATE: ${{ secrets.FRPC_TLS_CA_CERTIFICATE }}
          SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
