name: Windows
on:
  workflow_dispatch:
    inputs:
      Windows:
        type: choice
        description: Windows dist the workflow will run on
        required: true
        default: windows-2022
        options: 
          - windows-2019
          - windows-2022
      ssh:
        type: boolean
        description: Install OpenSSH
        required: true
        default: false
      pagefile_d:
        type: boolean
        description: "Use larger pagefile (13GB) on D:"
        required: true
        default: true
      pagefile_c:
        type: boolean
        description: "Use larger pagefile (12GB) on C:"
        required: true
        default: false
jobs:
  build:
    runs-on: ${{ github.event.inputs.Windows }}
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - if: ${{ inputs.pagefile_d }}
        uses: al-cheb/configure-pagefile-action@v1.3
        with:
          minimum-size: 13GB
          # maximum-size: 13GB
          disk-root: "D:"
      - if: ${{ inputs.pagefile_c }}
        uses: al-cheb/configure-pagefile-action@v1.3
        with:
          minimum-size: 12GB
          # maximum-size: 12GB
          disk-root: "C:"
      - run: ./init.ps1
        env:
          INIT_SSH: ${{ inputs.ssh }}
      - run: ./run-frpc.ps1
        env:
          RUNNER_PASSWORD: ${{ secrets.RUNNER_PASSWORD }}
          FRPS_DOMAIN: ${{ secrets.FRPS_DOMAIN }}
          FRPC_TLS_KEY: ${{ secrets.FRPC_TLS_KEY }}
          FRPC_TLS_CERTIFICATE: ${{ secrets.FRPC_TLS_CERTIFICATE }}
          FRPC_TLS_CA_CERTIFICATE: ${{ secrets.FRPC_TLS_CA_CERTIFICATE }}
          SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
