name: Windows
on:
  workflow_dispatch:
    inputs:
      Windows:
        type: choice
        description: Windows dist the workflow will run on
        required: true
        default: windows-2022
        options: 
          - windows-2019
          - windows-2022
jobs:
  build:
    runs-on: ${{ github.event.inputs.Windows }}
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - run: ./init.ps1
      - run: ./install-frp.ps1
      - name: run frpc
        env:
          RUNNER_PASSWORD: ${{ secrets.RUNNER_PASSWORD }}
          FRPS_DOMAIN: ${{ secrets.FRPS_DOMAIN }}
          FRPC_TLS_KEY: ${{ secrets.FRPC_TLS_KEY }}
          FRPC_TLS_CERTIFICATE: ${{ secrets.FRPC_TLS_CERTIFICATE }}
          FRPC_TLS_CA_CERTIFICATE: ${{ secrets.FRPC_TLS_CA_CERTIFICATE }}
          SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
        run: ./run-frpc.ps1
